export const FOOD_DATABASE = [

  // ── BREAKFAST FOODS ──────────────────────────────────────
  { id:1,   name:'Scrambled Eggs (2 large)',         cal:182, p:12, c:2,  f:14, category:'Breakfast' },
  { id:2,   name:'Fried Eggs (2 large)',             cal:185, p:13, c:1,  f:14, category:'Breakfast' },
  { id:3,   name:'Hard Boiled Eggs (2)',             cal:155, p:13, c:1,  f:11, category:'Breakfast' },
  { id:4,   name:'Oatmeal (1 cup cooked)',           cal:166, p:6,  c:28, f:4,  category:'Breakfast' },
  { id:5,   name:'Overnight Oats (1 cup)',           cal:215, p:8,  c:35, f:5,  category:'Breakfast' },
  { id:6,   name:'Pancakes (3 medium)',              cal:350, p:9,  c:55, f:10, category:'Breakfast' },
  { id:7,   name:'Waffles (2 medium)',               cal:310, p:8,  c:50, f:9,  category:'Breakfast' },
  { id:8,   name:'French Toast (2 slices)',          cal:270, p:9,  c:38, f:9,  category:'Breakfast' },
  { id:9,   name:'Bagel (plain)',                    cal:270, p:11, c:53, f:1,  category:'Breakfast' },
  { id:10,  name:'Bagel with Cream Cheese',          cal:370, p:12, c:53, f:13, category:'Breakfast' },
  { id:11,  name:'English Muffin (1)',               cal:134, p:5,  c:26, f:1,  category:'Breakfast' },
  { id:12,  name:'Croissant (1 medium)',             cal:272, p:5,  c:31, f:14, category:'Breakfast' },
  { id:13,  name:'Avocado Toast (1 slice)',          cal:195, p:4,  c:20, f:11, category:'Breakfast' },
  { id:14,  name:'Greek Yogurt (1 cup plain)',       cal:130, p:22, c:9,  f:0,  category:'Breakfast' },
  { id:15,  name:'Greek Yogurt (1 cup flavored)',    cal:180, p:17, c:25, f:0,  category:'Breakfast' },
  { id:16,  name:'Granola (½ cup)',                  cal:210, p:5,  c:35, f:7,  category:'Breakfast' },
  { id:17,  name:'Granola Bar (1)',                  cal:190, p:4,  c:29, f:7,  category:'Breakfast' },
  { id:18,  name:'Breakfast Burrito',                cal:380, p:17, c:42, f:15, category:'Breakfast' },
  { id:19,  name:'Bacon (3 strips)',                 cal:130, p:10, c:0,  f:10, category:'Breakfast' },
  { id:20,  name:'Turkey Bacon (3 strips)',          cal:70,  p:9,  c:1,  f:3,  category:'Breakfast' },
  { id:21,  name:'Sausage Link (2)',                 cal:170, p:8,  c:1,  f:15, category:'Breakfast' },
  { id:22,  name:'Hash Browns (½ cup)',              cal:150, p:2,  c:20, f:7,  category:'Breakfast' },
  { id:23,  name:'Smoothie Bowl',                   cal:320, p:8,  c:58, f:6,  category:'Breakfast' },

  // ── CEREALS ──────────────────────────────────────────────
  { id:24,  name:'Cheerios (1 cup)',                 cal:100, p:3,  c:20, f:2,  category:'Cereal' },
  { id:25,  name:'Honey Nut Cheerios (1 cup)',       cal:140, p:3,  c:29, f:2,  category:'Cereal' },
  { id:26,  name:'Frosted Flakes (¾ cup)',           cal:110, p:1,  c:27, f:0,  category:'Cereal' },
  { id:27,  name:'Cocoa Puffs (¾ cup)',              cal:110, p:1,  c:25, f:1,  category:'Cereal' },
  { id:28,  name:'Lucky Charms (¾ cup)',             cal:110, p:2,  c:25, f:1,  category:'Cereal' },
  { id:29,  name:'Frosted Mini Wheats (1 cup)',      cal:190, p:5,  c:45, f:1,  category:'Cereal' },
  { id:30,  name:'Raisin Bran (1 cup)',              cal:190, p:5,  c:46, f:2,  category:'Cereal' },
  { id:31,  name:'Special K (1 cup)',                cal:120, p:6,  c:23, f:0,  category:'Cereal' },
  { id:32,  name:'Corn Flakes (1 cup)',              cal:100, p:2,  c:24, f:0,  category:'Cereal' },
  { id:33,  name:'Froot Loops (1 cup)',              cal:110, p:1,  c:26, f:1,  category:'Cereal' },
  { id:34,  name:'Cap'n Crunch (¾ cup)',            cal:110, p:1,  c:24, f:1,  category:'Cereal' },

  // ── PROTEINS ─────────────────────────────────────────────
  { id:35,  name:'Chicken Breast (4oz grilled)',     cal:185, p:35, c:0,  f:4,  category:'Protein' },
  { id:36,  name:'Chicken Breast (6oz grilled)',     cal:280, p:52, c:0,  f:6,  category:'Protein' },
  { id:37,  name:'Chicken Thigh (4oz)',              cal:209, p:26, c:0,  f:11, category:'Protein' },
  { id:38,  name:'Chicken Wings (4 pieces)',         cal:290, p:24, c:0,  f:20, category:'Protein' },
  { id:39,  name:'Ground Beef 80/20 (4oz)',          cal:285, p:20, c:0,  f:22, category:'Protein' },
  { id:40,  name:'Ground Beef 93/7 (4oz)',           cal:200, p:25, c:0,  f:11, category:'Protein' },
  { id:41,  name:'Ground Turkey (4oz)',              cal:170, p:23, c:0,  f:9,  category:'Protein' },
  { id:42,  name:'Steak Sirloin (6oz)',              cal:320, p:46, c:0,  f:14, category:'Protein' },
  { id:43,  name:'Ribeye Steak (6oz)',               cal:450, p:40, c:0,  f:31, category:'Protein' },
  { id:44,  name:'Salmon (6oz)',                     cal:280, p:38, c:0,  f:13, category:'Protein' },
  { id:45,  name:'Tilapia (6oz)',                    cal:165, p:34, c:0,  f:3,  category:'Protein' },
  { id:46,  name:'Shrimp (4oz)',                     cal:112, p:24, c:1,  f:1,  category:'Protein' },
  { id:47,  name:'Tuna (can in water)',              cal:109, p:25, c:0,  f:1,  category:'Protein' },
  { id:48,  name:'Tuna (can in oil)',                cal:168, p:25, c:0,  f:7,  category:'Protein' },
  { id:49,  name:'Turkey Breast (4oz)',              cal:130, p:28, c:0,  f:2,  category:'Protein' },
  { id:50,  name:'Pork Chop (4oz)',                  cal:195, p:27, c:0,  f:9,  category:'Protein' },
  { id:51,  name:'Pork Tenderloin (4oz)',            cal:150, p:26, c:0,  f:4,  category:'Protein' },
  { id:52,  name:'Cod (6oz)',                        cal:140, p:30, c:0,  f:1,  category:'Protein' },
  { id:53,  name:'Mahi Mahi (6oz)',                  cal:185, p:36, c:0,  f:2,  category:'Protein' },
  { id:54,  name:'Lamb Chop (4oz)',                  cal:250, p:26, c:0,  f:16, category:'Protein' },
  { id:55,  name:'Bison Burger (4oz)',               cal:200, p:24, c:0,  f:11, category:'Protein' },
  { id:56,  name:'Whole Eggs (1)',                   cal:72,  p:6,  c:0,  f:5,  category:'Protein' },
  { id:57,  name:'Egg Whites (3)',                   cal:51,  p:11, c:1,  f:0,  category:'Protein' },

  // ── PROTEIN SUPPLEMENTS ───────────────────────────────────
  { id:58,  name:'Whey Protein Shake',               cal:120, p:25, c:3,  f:2,  category:'Supplements' },
  { id:59,  name:'Casein Protein Shake',             cal:130, p:25, c:5,  f:1,  category:'Supplements' },
  { id:60,  name:'Plant Protein Shake',              cal:130, p:22, c:7,  f:3,  category:'Supplements' },
  { id:61,  name:'Mass Gainer Shake',                cal:650, p:40, c:110,f:8,  category:'Supplements' },
  { id:62,  name:'Protein Bar (Quest)',              cal:200, p:21, c:21, f:8,  category:'Supplements' },
  { id:63,  name:'Protein Bar (Kind)',               cal:250, p:12, c:24, f:11, category:'Supplements' },
  { id:64,  name:'Protein Bar (Clif)',               cal:250, p:11, c:45, f:6,  category:'Supplements' },
  { id:65,  name:'Protein Bar (RXBar)',              cal:210, p:12, c:24, f:9,  category:'Supplements' },
  { id:66,  name:'Protein Bar (ONE Bar)',            cal:220, p:20, c:24, f:7,  category:'Supplements' },

  // ── GRAINS & CARBS ────────────────────────────────────────
  { id:67,  name:'White Rice (1 cup cooked)',        cal:206, p:4,  c:45, f:0,  category:'Grains' },
  { id:68,  name:'Brown Rice (1 cup cooked)',        cal:216, p:5,  c:45, f:2,  category:'Grains' },
  { id:69,  name:'Jasmine Rice (1 cup)',             cal:210, p:4,  c:46, f:0,  category:'Grains' },
  { id:70,  name:'Quinoa (1 cup cooked)',            cal:222, p:8,  c:39, f:4,  category:'Grains' },
  { id:71,  name:'Pasta (1 cup cooked)',             cal:220, p:8,  c:43, f:1,  category:'Grains' },
  { id:72,  name:'Whole Wheat Pasta (1 cup)',        cal:174, p:7,  c:37, f:1,  category:'Grains' },
  { id:73,  name:'White Bread (1 slice)',            cal:67,  p:2,  c:13, f:1,  category:'Grains' },
  { id:74,  name:'Whole Wheat Bread (1 slice)',      cal:69,  p:4,  c:12, f:1,  category:'Grains' },
  { id:75,  name:'Sourdough Bread (1 slice)',        cal:90,  p:4,  c:17, f:1,  category:'Grains' },
  { id:76,  name:'Flour Tortilla (1 large)',         cal:218, p:6,  c:36, f:6,  category:'Grains' },
  { id:77,  name:'Corn Tortilla (2 small)',          cal:100, p:3,  c:20, f:1,  category:'Grains' },
  { id:78,  name:'Oatmeal dry (½ cup)',              cal:150, p:5,  c:27, f:3,  category:'Grains' },
  { id:79,  name:'Sweet Potato (medium)',            cal:103, p:2,  c:24, f:0,  category:'Grains' },
  { id:80,  name:'Baked Potato (medium)',            cal:161, p:4,  c:37, f:0,  category:'Grains' },
  { id:81,  name:'French Fries (medium)',            cal:365, p:4,  c:48, f:17, category:'Grains' },
  { id:82,  name:'Mashed Potatoes (1 cup)',          cal:237, p:4,  c:35, f:9,  category:'Grains' },
  { id:83,  name:'Corn (1 cup)',                     cal:132, p:5,  c:29, f:2,  category:'Grains' },
  { id:84,  name:'Pita Bread (1 whole)',             cal:165, p:5,  c:33, f:1,  category:'Grains' },
  { id:85,  name:'Naan (1 piece)',                   cal:262, p:9,  c:45, f:5,  category:'Grains' },
  { id:86,  name:'Ramen Noodles (1 pack)',           cal:380, p:8,  c:52, f:14, category:'Grains' },
  { id:87,  name:'Mac and Cheese (1 cup)',           cal:350, p:12, c:50, f:11, category:'Grains' },

  // ── VEGETABLES ────────────────────────────────────────────
  { id:88,  name:'Broccoli (1 cup)',                 cal:55,  p:4,  c:11, f:1,  category:'Vegetables' },
  { id:89,  name:'Spinach (1 cup raw)',              cal:7,   p:1,  c:1,  f:0,  category:'Vegetables' },
  { id:90,  name:'Kale (1 cup)',                     cal:33,  p:2,  c:6,  f:1,  category:'Vegetables' },
  { id:91,  name:'Carrots (1 cup)',                  cal:52,  p:1,  c:12, f:0,  category:'Vegetables' },
  { id:92,  name:'Green Beans (1 cup)',              cal:31,  p:2,  c:7,  f:0,  category:'Vegetables' },
  { id:93,  name:'Asparagus (1 cup)',                cal:27,  p:3,  c:5,  f:0,  category:'Vegetables' },
  { id:94,  name:'Bell Pepper (1 medium)',           cal:37,  p:1,  c:9,  f:0,  category:'Vegetables' },
  { id:95,  name:'Cucumber (1 cup)',                 cal:16,  p:1,  c:4,  f:0,  category:'Vegetables' },
  { id:96,  name:'Tomato (1 medium)',                cal:22,  p:1,  c:5,  f:0,  category:'Vegetables' },
  { id:97,  name:'Lettuce (2 cups)',                 cal:10,  p:1,  c:2,  f:0,  category:'Vegetables' },
  { id:98,  name:'Celery (1 cup)',                   cal:16,  p:1,  c:3,  f:0,  category:'Vegetables' },
  { id:99,  name:'Mushrooms (1 cup)',                cal:15,  p:2,  c:2,  f:0,  category:'Vegetables' },
  { id:100, name:'Onion (1 medium)',                 cal:44,  p:1,  c:10, f:0,  category:'Vegetables' },
  { id:101, name:'Zucchini (1 cup)',                 cal:21,  p:2,  c:4,  f:0,  category:'Vegetables' },
  { id:102, name:'Cauliflower (1 cup)',              cal:25,  p:2,  c:5,  f:0,  category:'Vegetables' },
  { id:103, name:'Brussels Sprouts (1 cup)',         cal:56,  p:4,  c:11, f:1,  category:'Vegetables' },
  { id:104, name:'Edamame (1 cup)',                  cal:188, p:17, c:14, f:8,  category:'Vegetables' },
  { id:105, name:'Peas (1 cup)',                     cal:117, p:8,  c:21, f:1,  category:'Vegetables' },

  // ── FRUITS ────────────────────────────────────────────────
  { id:106, name:'Apple (medium)',                   cal:95,  p:0,  c:25, f:0,  category:'Fruit' },
  { id:107, name:'Banana (medium)',                  cal:105, p:1,  c:27, f:0,  category:'Fruit' },
  { id:108, name:'Orange (medium)',                  cal:62,  p:1,  c:15, f:0,  category:'Fruit' },
  { id:109, name:'Strawberries (1 cup)',             cal:49,  p:1,  c:12, f:0,  category:'Fruit' },
  { id:110, name:'Blueberries (1 cup)',              cal:84,  p:1,  c:21, f:0,  category:'Fruit' },
  { id:111, name:'Grapes (1 cup)',                   cal:104, p:1,  c:27, f:0,  category:'Fruit' },
  { id:112, name:'Watermelon (1 cup)',               cal:46,  p:1,  c:12, f:0,  category:'Fruit' },
  { id:113, name:'Mango (1 cup)',                    cal:107, p:1,  c:28, f:0,  category:'Fruit' },
  { id:114, name:'Pineapple (1 cup)',                cal:83,  p:1,  c:22, f:0,  category:'Fruit' },
  { id:115, name:'Avocado (half)',                   cal:161, p:2,  c:9,  f:15, category:'Fruit' },
  { id:116, name:'Peach (medium)',                   cal:59,  p:1,  c:14, f:0,  category:'Fruit' },
  { id:117, name:'Pear (medium)',                    cal:101, p:1,  c:27, f:0,  category:'Fruit' },
  { id:118, name:'Kiwi (1)',                         cal:42,  p:1,  c:10, f:0,  category:'Fruit' },
  { id:119, name:'Raspberries (1 cup)',              cal:64,  p:1,  c:15, f:1,  category:'Fruit' },
  { id:120, name:'Blackberries (1 cup)',             cal:62,  p:2,  c:14, f:1,  category:'Fruit' },
  { id:121, name:'Cherries (1 cup)',                 cal:87,  p:1,  c:22, f:0,  category:'Fruit' },
  { id:122, name:'Grapefruit (half)',                cal:52,  p:1,  c:13, f:0,  category:'Fruit' },
  { id:123, name:'Pomegranate (½ cup seeds)',        cal:83,  p:1,  c:19, f:1,  category:'Fruit' },

  // ── DAIRY ─────────────────────────────────────────────────
  { id:124, name:'Whole Milk (1 cup)',               cal:149, p:8,  c:12, f:8,  category:'Dairy' },
  { id:125, name:'2% Milk (1 cup)',                  cal:122, p:8,  c:12, f:5,  category:'Dairy' },
  { id:126, name:'Skim Milk (1 cup)',                cal:83,  p:8,  c:12, f:0,  category:'Dairy' },
  { id:127, name:'Almond Milk (1 cup)',              cal:30,  p:1,  c:1,  f:3,  category:'Dairy' },
  { id:128, name:'Oat Milk (1 cup)',                 cal:120, p:3,  c:16, f:5,  category:'Dairy' },
  { id:129, name:'Cheddar Cheese (1oz)',             cal:113, p:7,  c:0,  f:9,  category:'Dairy' },
  { id:130, name:'Mozzarella (1oz)',                 cal:85,  p:6,  c:1,  f:6,  category:'Dairy' },
  { id:131, name:'Cottage Cheese (½ cup)',           cal:110, p:14, c:4,  f:5,  category:'Dairy' },
  { id:132, name:'Cream Cheese (2 tbsp)',            cal:99,  p:2,  c:1,  f:10, category:'Dairy' },
  { id:133, name:'Butter (1 tbsp)',                  cal:102, p:0,  c:0,  f:12, category:'Dairy' },
  { id:134, name:'Sour Cream (2 tbsp)',              cal:61,  p:1,  c:2,  f:6,  category:'Dairy' },
  { id:135, name:'Heavy Cream (1 tbsp)',             cal:52,  p:0,  c:0,  f:6,  category:'Dairy' },
  { id:136, name:'Parmesan (1 tbsp)',                cal:22,  p:2,  c:0,  f:1,  category:'Dairy' },
  { id:137, name:'Feta Cheese (1oz)',                cal:75,  p:4,  c:1,  f:6,  category:'Dairy' },
  { id:138, name:'String Cheese (1)',                cal:80,  p:7,  c:1,  f:5,  category:'Dairy' },
  { id:139, name:'Yogurt Regular (1 cup)',           cal:149, p:8,  c:17, f:8,  category:'Dairy' },
  { id:140, name:'Skyr Yogurt (1 cup)',              cal:120, p:20, c:8,  f:0,  category:'Dairy' },

  // ── NUTS & SEEDS ──────────────────────────────────────────
  { id:141, name:'Almonds (1oz / 23 nuts)',          cal:164, p:6,  c:6,  f:14, category:'Nuts' },
  { id:142, name:'Cashews (1oz)',                    cal:157, p:5,  c:9,  f:12, category:'Nuts' },
  { id:143, name:'Walnuts (1oz)',                    cal:185, p:4,  c:4,  f:18, category:'Nuts' },
  { id:144, name:'Pistachios (1oz)',                 cal:159, p:6,  c:8,  f:13, category:'Nuts' },
  { id:145, name:'Peanuts (1oz)',                    cal:161, p:7,  c:5,  f:14, category:'Nuts' },
  { id:146, name:'Pecans (1oz)',                     cal:196, p:3,  c:4,  f:20, category:'Nuts' },
  { id:147, name:'Macadamia Nuts (1oz)',             cal:204, p:2,  c:4,  f:21, category:'Nuts' },
  { id:148, name:'Peanut Butter (2 tbsp)',           cal:190, p:8,  c:6,  f:16, category:'Nuts' },
  { id:149, name:'Almond Butter (2 tbsp)',           cal:196, p:7,  c:6,  f:18, category:'Nuts' },
  { id:150, name:'Sunflower Seeds (1oz)',            cal:165, p:5,  c:7,  f:14, category:'Nuts' },
  { id:151, name:'Chia Seeds (1 tbsp)',              cal:58,  p:2,  c:5,  f:4,  category:'Nuts' },
  { id:152, name:'Flax Seeds (1 tbsp)',              cal:55,  p:2,  c:3,  f:4,  category:'Nuts' },
  { id:153, name:'Hemp Seeds (3 tbsp)',              cal:166, p:10, c:3,  f:13, category:'Nuts' },
  { id:154, name:'Trail Mix (¼ cup)',                cal:173, p:5,  c:17, f:10, category:'Nuts' },

  // ── LEGUMES ───────────────────────────────────────────────
  { id:155, name:'Black Beans (½ cup)',              cal:114, p:8,  c:20, f:0,  category:'Legumes' },
  { id:156, name:'Chickpeas (½ cup)',                cal:134, p:7,  c:22, f:2,  category:'Legumes' },
  { id:157, name:'Lentils (½ cup cooked)',           cal:115, p:9,  c:20, f:0,  category:'Legumes' },
  { id:158, name:'Kidney Beans (½ cup)',             cal:112, p:8,  c:20, f:0,  category:'Legumes' },
  { id:159, name:'Pinto Beans (½ cup)',              cal:122, p:8,  c:22, f:1,  category:'Legumes' },
  { id:160, name:'White Beans (½ cup)',              cal:125, p:9,  c:23, f:0,  category:'Legumes' },
  { id:161, name:'Tofu (½ cup firm)',                cal:94,  p:10, c:2,  f:5,  category:'Legumes' },
  { id:162, name:'Tempeh (3oz)',                     cal:160, p:15, c:8,  f:9,  category:'Legumes' },

  // ── FAST FOOD ─────────────────────────────────────────────
  { id:163, name:'McDonald's Big Mac',              cal:550, p:25, c:46, f:30, category:'Fast Food' },
  { id:164, name:'McDonald's McDouble',             cal:400, p:22, c:36, f:19, category:'Fast Food' },
  { id:165, name:'McDonald's Quarter Pounder',      cal:520, p:30, c:41, f:26, category:'Fast Food' },
  { id:166, name:'McDonald's Chicken McNuggets 10', cal:440, p:27, c:27, f:27, category:'Fast Food' },
  { id:167, name:'McDonald's Medium Fries',         cal:320, p:4,  c:44, f:15, category:'Fast Food' },
  { id:168, name:'McDonald's McChicken',            cal:400, p:14, c:40, f:20, category:'Fast Food' },
  { id:169, name:'Chick-fil-A Sandwich',             cal:440, p:28, c:41, f:19, category:'Fast Food' },
  { id:170, name:'Chick-fil-A Nuggets (8pc)',        cal:250, p:29, c:11, f:11, category:'Fast Food' },
  { id:171, name:'Chick-fil-A Waffle Fries (med)',   cal:360, p:5,  c:45, f:18, category:'Fast Food' },
  { id:172, name:'Wendy's Baconator',               cal:950, p:58, c:37, f:62, category:'Fast Food' },
  { id:173, name:'Wendy's Dave's Single',          cal:570, p:30, c:40, f:31, category:'Fast Food' },
  { id:174, name:'Burger King Whopper',              cal:670, p:28, c:51, f:40, category:'Fast Food' },
  { id:175, name:'Burger King Chicken Fries (9pc)',  cal:280, p:15, c:25, f:13, category:'Fast Food' },
  { id:176, name:'Subway 6" Turkey Sub',             cal:280, p:18, c:46, f:5,  category:'Fast Food' },
  { id:177, name:'Subway 6" Chicken Teriyaki',       cal:373, p:26, c:53, f:7,  category:'Fast Food' },
  { id:178, name:'Chipotle Burrito Bowl (chicken)',  cal:665, p:51, c:68, f:22, category:'Fast Food' },
  { id:179, name:'Chipotle Burrito (steak)',         cal:900, p:47, c:89, f:35, category:'Fast Food' },
  { id:180, name:'Taco Bell Crunchy Taco',           cal:170, p:8,  c:13, f:10, category:'Fast Food' },
  { id:181, name:'Taco Bell Burrito Supreme',        cal:390, p:16, c:51, f:15, category:'Fast Food' },
  { id:182, name:'Taco Bell Chalupa Supreme',        cal:350, p:13, c:34, f:18, category:'Fast Food' },
  { id:183, name:'Domino's Pepperoni Pizza (2 sl)', cal:540, p:22, c:60, f:24, category:'Fast Food' },
  { id:184, name:'Pizza Hut Pepperoni Pizza (2 sl)', cal:520, p:22, c:56, f:22, category:'Fast Food' },
  { id:185, name:'Papa John's Original (2 slices)', cal:500, p:20, c:58, f:20, category:'Fast Food' },
  { id:186, name:'KFC Original Chicken (breast)',    cal:390, p:39, c:11, f:21, category:'Fast Food' },
  { id:187, name:'KFC Chicken Sandwich',             cal:650, p:34, c:56, f:30, category:'Fast Food' },
  { id:188, name:'Panda Express Orange Chicken',     cal:420, p:15, c:57, f:15, category:'Fast Food' },
  { id:189, name:'Panda Express Fried Rice',         cal:620, p:18, c:98, f:18, category:'Fast Food' },
  { id:190, name:'Panera Broccoli Cheddar Soup',     cal:360, p:14, c:30, f:22, category:'Fast Food' },
  { id:191, name:'Panera Turkey Sandwich',           cal:450, p:27, c:56, f:13, category:'Fast Food' },
  { id:192, name:'Sonic Cheeseburger',               cal:600, p:28, c:44, f:36, category:'Fast Food' },
  { id:193, name:'Five Guys Burger',                 cal:700, p:35, c:39, f:43, category:'Fast Food' },
  { id:194, name:'Popeyes Chicken Sandwich',         cal:700, p:28, c:50, f:42, category:'Fast Food' },
  { id:195, name:'Raising Cane's Box Combo',        cal:1000,p:50, c:72, f:54, category:'Fast Food' },
  { id:196, name:'Shake Shack ShackBurger',          cal:530, p:26, c:40, f:31, category:'Fast Food' },
  { id:197, name:'In-N-Out Double Double',           cal:670, p:37, c:39, f:41, category:'Fast Food' },
  { id:198, name:'Whataburger (original)',           cal:590, p:25, c:61, f:27, category:'Fast Food' },

  // ── SNACKS ────────────────────────────────────────────────
  { id:199, name:'Oreos (3 cookies)',                cal:160, p:1,  c:25, f:7,  category:'Snacks' },
  { id:200, name:'Double Stuf Oreos (2)',            cal:140, p:1,  c:21, f:6,  category:'Snacks' },
  { id:201, name:'Golden Oreos (3)',                 cal:160, p:1,  c:25, f:7,  category:'Snacks' },
  { id:202, name:'Chips Ahoy (3 cookies)',           cal:160, p:2,  c:22, f:8,  category:'Snacks' },
  { id:203, name:'Chocolate Chip Cookies (2)',       cal:178, p:2,  c:24, f:9,  category:'Snacks' },
  { id:204, name:'Lay's Classic Chips (1oz)',       cal:160, p:2,  c:15, f:10, category:'Snacks' },
  { id:205, name:'Doritos Nacho (1oz)',              cal:140, p:2,  c:18, f:8,  category:'Snacks' },
  { id:206, name:'Cheetos (1oz)',                    cal:160, p:2,  c:15, f:10, category:'Snacks' },
  { id:207, name:'Pringles (15 chips)',              cal:150, p:1,  c:15, f:9,  category:'Snacks' },
  { id:208, name:'Pretzels (1oz)',                   cal:108, p:3,  c:23, f:1,  category:'Snacks' },
  { id:209, name:'Popcorn (3 cups air popped)',      cal:93,  p:3,  c:19, f:1,  category:'Snacks' },
  { id:210, name:'Popcorn (movie theater med)',      cal:630, p:8,  c:70, f:34, category:'Snacks' },
  { id:211, name:'Rice Cakes (2)',                   cal:70,  p:1,  c:15, f:0,  category:'Snacks' },
  { id:212, name:'Crackers Ritz (5)',                cal:80,  p:1,  c:10, f:4,  category:'Snacks' },
  { id:213, name:'Goldfish Crackers (55 pieces)',    cal:140, p:3,  c:20, f:5,  category:'Snacks' },
  { id:214, name:'Animal Crackers (16)',             cal:130, p:2,  c:22, f:4,  category:'Snacks' },
  { id:215, name:'Fruit Snacks (1 pouch)',           cal:80,  p:0,  c:19, f:0,  category:'Snacks' },
  { id:216, name:'Fruit Roll-Up (1)',                cal:50,  p:0,  c:12, f:1,  category:'Snacks' },
  { id:217, name:'Pop-Tart (1)',                     cal:200, p:2,  c:37, f:5,  category:'Snacks' },
  { id:218, name:'Nature Valley Bar (1)',            cal:190, p:4,  c:29, f:7,  category:'Snacks' },
  { id:219, name:'Nutri-Grain Bar (1)',              cal:130, p:2,  c:26, f:3,  category:'Snacks' },
  { id:220, name:'Fiber One Bar (1)',                cal:90,  p:2,  c:24, f:2,  category:'Snacks' },
  { id:221, name:'Slim Jim (1 stick)',               cal:80,  p:4,  c:1,  f:7,  category:'Snacks' },
  { id:222, name:'Beef Jerky (1oz)',                 cal:116, p:9,  c:3,  f:7,  category:'Snacks' },
  { id:223, name:'Sunflower Seeds (1oz shell)',      cal:165, p:6,  c:7,  f:14, category:'Snacks' },
  { id:224, name:'Hummus (2 tbsp)',                  cal:70,  p:2,  c:6,  f:5,  category:'Snacks' },
  { id:225, name:'Guacamole (2 tbsp)',               cal:45,  p:1,  c:3,  f:4,  category:'Snacks' },
  { id:226, name:'Salsa (2 tbsp)',                   cal:10,  p:0,  c:2,  f:0,  category:'Snacks' },
  { id:227, name:'Queso Dip (2 tbsp)',               cal:80,  p:2,  c:4,  f:6,  category:'Snacks' },

  // ── CANDY & SWEETS ────────────────────────────────────────
  { id:228, name:'Snickers Bar (fun size)',          cal:80,  p:1,  c:11, f:4,  category:'Candy' },
  { id:229, name:'Snickers Bar (regular)',           cal:250, p:4,  c:33, f:12, category:'Candy' },
  { id:230, name:'M&Ms (fun size)',                  cal:90,  p:1,  c:13, f:4,  category:'Candy' },
  { id:231, name:'M&Ms (regular bag)',               cal:240, p:2,  c:34, f:10, category:'Candy' },
  { id:232, name:'Reese's PB Cups (2)',             cal:210, p:5,  c:25, f:12, category:'Candy' },
  { id:233, name:'Kit Kat Bar (2 fingers)',          cal:210, p:3,  c:27, f:11, category:'Candy' },
  { id:234, name:'Twix Bar (1 bar)',                 cal:250, p:2,  c:34, f:12, category:'Candy' },
  { id:235, name:'Milky Way (regular)',              cal:240, p:2,  c:36, f:9,  category:'Candy' },
  { id:236, name:'3 Musketeers (regular)',           cal:240, p:2,  c:43, f:7,  category:'Candy' },
  { id:237, name:'Skittles (fun size)',              cal:80,  p:0,  c:19, f:1,  category:'Candy' },
  { id:238, name:'Starburst (4 pieces)',             cal:80,  p:0,  c:18, f:1,  category:'Candy' },
  { id:239, name:'Gummy Bears (17 pieces)',          cal:130, p:2,  c:30, f:0,  category:'Candy' },
  { id:240, name:'Swedish Fish (7 pieces)',          cal:100, p:0,  c:25, f:0,  category:'Candy' },
  { id:241, name:'Sour Patch Kids (9 pieces)',       cal:110, p:0,  c:28, f:0,  category:'Candy' },
  { id:242, name:'Jolly Rancher (3 pieces)',         cal:70,  p:0,  c:17, f:0,  category:'Candy' },
  { id:243, name:'Hershey's Chocolate Bar',        cal:220, p:3,  c:26, f:13, category:'Candy' },
  { id:244, name:'Dark Chocolate (1oz)',             cal:170, p:2,  c:13, f:12, category:'Candy' },
  { id:245, name:'Milk Chocolate (1oz)',             cal:153, p:2,  c:17, f:9,  category:'Candy' },
  { id:246, name:'Twizzlers (4 pieces)',             cal:160, p:1,  c:36, f:1,  category:'Candy' },

  // ── DESSERTS ──────────────────────────────────────────────
  { id:247, name:'Chocolate Cake (1 slice)',         cal:350, p:5,  c:50, f:15, category:'Desserts' },
  { id:248, name:'Cheesecake (1 slice)',             cal:400, p:7,  c:36, f:26, category:'Desserts' },
  { id:249, name:'Ice Cream (½ cup vanilla)',        cal:145, p:2,  c:17, f:8,  category:'Desserts' },
  { id:250, name:'Ice Cream (½ cup chocolate)',      cal:140, p:3,  c:18, f:7,  category:'Desserts' },
  { id:251, name:'Ben & Jerry's (½ cup)',           cal:250, p:4,  c:30, f:13, category:'Desserts' },
  { id:252, name:'Halo Top Ice Cream (½ cup)',       cal:70,  p:6,  c:12, f:2,  category:'Desserts' },
  { id:253, name:'Brownie (1 square)',               cal:240, p:3,  c:36, f:10, category:'Desserts' },
  { id:254, name:'Donut (glazed)',                   cal:260, p:4,  c:31, f:14, category:'Desserts' },
  { id:255, name:'Donut (chocolate frosted)',        cal:300, p:4,  c:36, f:16, category:'Desserts' },
  { id:256, name:'Muffin (blueberry)',               cal:340, p:5,  c:54, f:12, category:'Desserts' },
  { id:257, name:'Cinnamon Roll (1)',                cal:310, p:5,  c:47, f:12, category:'Desserts' },
  { id:258, name:'Apple Pie (1 slice)',              cal:411, p:4,  c:58, f:19, category:'Desserts' },
  { id:259, name:'Pumpkin Pie (1 slice)',            cal:316, p:7,  c:41, f:14, category:'Desserts' },
  { id:260, name:'Jell-O (½ cup)',                   cal:80,  p:2,  c:19, f:0,  category:'Desserts' },
  { id:261, name:'Pudding Cup',                     cal:100, p:1,  c:22, f:1,  category:'Desserts' },

  // ── BEVERAGES ─────────────────────────────────────────────
  { id:262, name:'Coca-Cola (12oz can)',             cal:140, p:0,  c:39, f:0,  category:'Beverages' },
  { id:263, name:'Diet Coke (12oz)',                 cal:0,   p:0,  c:0,  f:0,  category:'Beverages' },
  { id:264, name:'Pepsi (12oz)',                     cal:150, p:0,  c:41, f:0,  category:'Beverages' },
  { id:265, name:'Sprite (12oz)',                    cal:140, p:0,  c:38, f:0,  category:'Beverages' },
  { id:266, name:'Mountain Dew (12oz)',              cal:170, p:0,  c:46, f:0,  category:'Beverages' },
  { id:267, name:'Dr Pepper (12oz)',                 cal:150, p:0,  c:40, f:0,  category:'Beverages' },
  { id:268, name:'Orange Juice (8oz)',               cal:112, p:2,  c:26, f:0,  category:'Beverages' },
  { id:269, name:'Apple Juice (8oz)',                cal:114, p:0,  c:28, f:0,  category:'Beverages' },
  { id:270, name:'Gatorade (20oz)',                  cal:140, p:0,  c:36, f:0,  category:'Beverages' },
  { id:271, name:'Powerade (20oz)',                  cal:130, p:0,  c:34, f:0,  category:'Beverages' },
  { id:272, name:'Red Bull (8.4oz)',                 cal:110, p:1,  c:28, f:0,  category:'Beverages' },
  { id:273, name:'Monster Energy (16oz)',            cal:210, p:0,  c:54, f:0,  category:'Beverages' },
  { id:274, name:'Celsius Energy (12oz)',            cal:10,  p:0,  c:2,  f:0,  category:'Beverages' },
  { id:275, name:'Coffee Black (8oz)',               cal:5,   p:0,  c:0,  f:0,  category:'Beverages' },
  { id:276, name:'Coffee with Cream (8oz)',          cal:60,  p:1,  c:5,  f:4,  category:'Beverages' },
  { id:277, name:'Latte (16oz whole milk)',          cal:190, p:11, c:18, f:7,  category:'Beverages' },
  { id:278, name:'Cappuccino (12oz)',                cal:120, p:7,  c:12, f:4,  category:'Beverages' },
  { id:279, name:'Starbucks Frappuccino (grande)',   cal:420, p:5,  c:65, f:16, category:'Beverages' },
  { id:280, name:'Starbucks PSL (grande)',           cal:380, p:14, c:52, f:14, category:'Beverages' },
  { id:281, name:'Chocolate Milk (8oz)',             cal:208, p:8,  c:31, f:8,  category:'Beverages' },
  { id:282, name:'Protein Shake (Fairlife)',         cal:160, p:30, c:6,  f:3,  category:'Beverages' },
  { id:283, name:'Water (8oz)',                      cal:0,   p:0,  c:0,  f:0,  category:'Beverages' },
  { id:284, name:'Coconut Water (8oz)',              cal:46,  p:2,  c:9,  f:0,  category:'Beverages' },
  { id:285, name:'Beer (12oz regular)',              cal:153, p:1,  c:13, f:0,  category:'Beverages' },
  { id:286, name:'Beer (12oz light)',                cal:103, p:1,  c:6,  f:0,  category:'Beverages' },
  { id:287, name:'Wine (5oz red)',                   cal:125, p:0,  c:4,  f:0,  category:'Beverages' },
  { id:288, name:'Wine (5oz white)',                 cal:121, p:0,  c:4,  f:0,  category:'Beverages' },
  { id:289, name:'Vodka Soda (8oz)',                 cal:100, p:0,  c:0,  f:0,  category:'Beverages' },

  // ── CONDIMENTS & SAUCES ───────────────────────────────────
  { id:290, name:'Ketchup (1 tbsp)',                 cal:20,  p:0,  c:5,  f:0,  category:'Condiments' },
  { id:291, name:'Mustard (1 tbsp)',                 cal:10,  p:1,  c:1,  f:0,  category:'Condiments' },
  { id:292, name:'Mayo (1 tbsp)',                    cal:94,  p:0,  c:0,  f:10, category:'Condiments' },
  { id:293, name:'Ranch Dressing (2 tbsp)',          cal:130, p:1,  c:2,  f:13, category:'Condiments' },
  { id:294, name:'Caesar Dressing (2 tbsp)',         cal:160, p:1,  c:1,  f:17, category:'Condiments' },
  { id:295, name:'Italian Dressing (2 tbsp)',        cal:86,  p:0,  c:3,  f:8,  category:'Condiments' },
  { id:296, name:'Olive Oil (1 tbsp)',               cal:119, p:0,  c:0,  f:14, category:'Condiments' },
  { id:297, name:'Soy Sauce (1 tbsp)',               cal:10,  p:1,  c:1,  f:0,  category:'Condiments' },
  { id:298, name:'Hot Sauce (1 tsp)',                cal:5,   p:0,  c:1,  f:0,  category:'Condiments' },
  { id:299, name:'BBQ Sauce (2 tbsp)',               cal:60,  p:0,  c:13, f:0,  category:'Condiments' },
  { id:300, name:'Sriracha (1 tbsp)',                cal:15,  p:0,  c:3,  f:0,  category:'Condiments' },
  { id:301, name:'Honey (1 tbsp)',                   cal:64,  p:0,  c:17, f:0,  category:'Condiments' },
  { id:302, name:'Maple Syrup (1 tbsp)',             cal:52,  p:0,  c:13, f:0,  category:'Condiments' },
  { id:303, name:'Nutella (2 tbsp)',                 cal:200, p:2,  c:23, f:11, category:'Condiments' },

  // ── RESTAURANT / MEALS ────────────────────────────────────
  { id:304, name:'Sushi Roll (8 pieces)',            cal:350, p:12, c:56, f:8,  category:'Restaurant' },
  { id:305, name:'Pad Thai (1 cup)',                 cal:400, p:16, c:52, f:15, category:'Restaurant' },
  { id:306, name:'Chicken Fried Rice (1 cup)',       cal:340, p:16, c:46, f:9,  category:'Restaurant' },
  { id:307, name:'General Tso's Chicken',          cal:430, p:19, c:44, f:20, category:'Restaurant' },
  { id:308, name:'Beef and Broccoli',                cal:310, p:23, c:18, f:17, category:'Restaurant' },
  { id:309, name:'Spaghetti Bolognese (1 cup)',      cal:380, p:20, c:48, f:12, category:'Restaurant' },
  { id:310, name:'Chicken Alfredo (1 cup)',          cal:480, p:28, c:44, f:20, category:'Restaurant' },
  { id:311, name:'Grilled Chicken Salad',            cal:350, p:35, c:18, f:15, category:'Restaurant' },
  { id:312, name:'Caesar Salad (full)',              cal:480, p:14, c:20, f:40, category:'Restaurant' },
  { id:313, name:'Chicken Quesadilla',               cal:520, p:28, c:44, f:25, category:'Restaurant' },
  { id:314, name:'Fish Tacos (2)',                   cal:380, p:22, c:40, f:14, category:'Restaurant' },
  { id:315, name:'Chicken Soup (1 cup)',             cal:120, p:12, c:14, f:3,  category:'Restaurant' },
  { id:316, name:'Tomato Soup (1 cup)',              cal:90,  p:2,  c:20, f:1,  category:'Restaurant' },
  { id:317, name:'Grilled Cheese Sandwich',          cal:400, p:15, c:40, f:21, category:'Restaurant' },
  { id:318, name:'BLT Sandwich',                    cal:420, p:18, c:36, f:22, category:'Restaurant' },
  { id:319, name:'Club Sandwich',                    cal:540, p:28, c:45, f:26, category:'Restaurant' },
  { id:320, name:'Chicken Wrap',                     cal:450, p:30, c:48, f:14, category:'Restaurant' },

  // ── FROZEN FOODS ──────────────────────────────────────────
  { id:321, name:'Hot Pocket (1)',                   cal:310, p:12, c:38, f:12, category:'Frozen' },
  { id:322, name:'Lean Cuisine (avg)',               cal:280, p:18, c:38, f:6,  category:'Frozen' },
  { id:323, name:'Amy's Frozen Burrito',            cal:290, p:10, c:44, f:8,  category:'Frozen' },
  { id:324, name:'Frozen Pizza (2 slices)',          cal:570, p:22, c:68, f:22, category:'Frozen' },
  { id:325, name:'Frozen Waffles (2)',               cal:190, p:5,  c:32, f:5,  category:'Frozen' },
  { id:326, name:'Frozen French Toast (2)',          cal:260, p:7,  c:40, f:8,  category:'Frozen' },
  { id:327, name:'Frozen Chicken Nuggets (5)',       cal:200, p:12, c:13, f:11, category:'Frozen' },
  { id:328, name:'Totino's Pizza Rolls (6)',        cal:210, p:7,  c:25, f:9,  category:'Frozen' },

  // ── OILS & FATS ───────────────────────────────────────────
  { id:329, name:'Coconut Oil (1 tbsp)',             cal:121, p:0,  c:0,  f:14, category:'Fats' },
  { id:330, name:'Avocado Oil (1 tbsp)',             cal:124, p:0,  c:0,  f:14, category:'Fats' },
  { id:331, name:'Canola Oil (1 tbsp)',              cal:124, p:0,  c:0,  f:14, category:'Fats' },
]

export function searchFoods(query) {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase()
  return FOOD_DATABASE.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.category.toLowerCase().includes(q)
  ).slice(0, 50)
}

export function getFoodsByCategory(category) {
  return FOOD_DATABASE.filter(f => f.category === category)
}

export const CATEGORIES = [...new Set(FOOD_DATABASE.map(f => f.category))]
